FROM ubuntu:jammy

#dif env
ENV MARIADB_PASS=password
ENV MARIADB_ROOT_PASS=rootpassword
ENV DOMAINS='example.com www.example.com example.dev'
ENV CERTBOT_MAIL=user@example.com
ENV CERTBOT_DOMAIN=example.com
ENV WP_HASH='wp-secret-config-hash'
#env
ENV TZ=UTC
ENV PHP_LIMIT=128M
ENV MARIADB_DB=wordpress_db
ENV MARIADB_USER=wordpress

#ini
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update

#php
RUN apt install php8.1-curl  -y
RUN apt install php8.1-gd  -y
RUN apt install php8.1-intl  -y
RUN apt install php8.1-mbstring  -y
RUN apt install php8.1-soap  -y
RUN apt install php8.1-xml  -y
RUN apt install php8.1-xmlrpc  -y
RUN apt install php8.1-zip -y
RUN apt install php8.1-fpm -y
RUN apt install php8.1-mysql -y
RUN sed -i "s/upload_max_filesize = 2M/upload_max_filesize = $PHP_LIMIT/g" /etc/php/8.1/fpm/php.ini
RUN sed -i "s/post_max_size = 8M/post_max_size = $PHP_LIMIT/g" /etc/php/8.1/fpm/php.ini

#db
RUN apt install mariadb-server -y
RUN apt install mariadb-client -y
ADD internal_sh/db_init_existing.sh /root/db_init.sh
COPY data/dump.sql dump.sql
RUN chmod 775 /root/db_init.sh
RUN /root/db_init.sh
RUN rm dump.sql

#nginx
RUN apt install nginx -y
COPY nginx-conf/site.conf /etc/nginx/sites-enabled/site.conf
RUN sed -i "s/DOMAINS/$DOMAINS/g" /etc/nginx/sites-enabled/site.conf
RUN sed -i "s/PHP_LIMIT/$PHP_LIMIT/g" /etc/nginx/sites-enabled/site.conf
RUN nginx -t

#certbot
RUN apt install certbot python3-certbot-nginx -y

#wordpress
RUN apt install unzip
COPY data/wordpress.zip wordpress.zip
RUN unzip wordpress.zip -d /var/www/
RUN chown -R www-data:www-data /var/www/wordpress/
RUN find /var/www/wordpress -type d -exec chmod 755 {} \;
RUN find /var/www/wordpress -type f -exec chmod 644 {} \;
RUN rm wordpress.zip
RUN sed -i "s/database_name_here/$MARIADB_DB/g" /var/www/wordpress/wp-config-sample.php
RUN sed -i "s/username_here/$MARIADB_USER/g" /var/www/wordpress/wp-config-sample.php
RUN sed -i "s/password_here/$MARIADB_PASS/g" /var/www/wordpress/wp-config-sample.php
RUN sed -i "s/put your unique phrase here/"$WP_HASH"/g" /var/www/wordpress/wp-config-sample.php
RUN cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

# run cmd add
ADD internal_sh/run.sh /root/run.sh
RUN chmod 775 /root/run.sh
RUN sed -i "s/CERTBOT_DOMAIN/$CERTBOT_DOMAIN/g" /root/run.sh
RUN sed -i "s/CERTBOT_MAIL/$CERTBOT_MAIL/g" /root/run.sh
CMD ["/root/run.sh"]
